# fly.toml app configuration file generated for marketprices-api on 2023-11-28T08:28:41-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marketprices-api"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]  
	release_command = "migrate -y"